ALTER TABLE tax_document DROP FOREIGN KEY FK_38FD2BC8E7A1254A;
ALTER TABLE tax_document ADD CONSTRAINT FK_38FD2BC8E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL;


--
--
--
INSERT INTO migration_versions (version)
VALUES ('20230706');